version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "messages.topic:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  rabbitmq:
    image: itzg/rabbitmq-stomp
    ports:
      - "15672:15672"
      - "5672:5672"
      - "61613:61613"
  
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis
    ports:
      - "6379:6379"