server:
  port: 8081

spring:
  application:    name: microservice-web
  redis:
    host: localhost
    port: 6379  datasource:    url: jdbc:mysql://localhost:3306/message_user
    username: message
    password: "1234"
    driver-class-name: com.mysql.cj.jdbc.Driver

  session:
    store-type: redis
    timeout: 2592000
    redis:      namespace: message:spring:session

  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
                rabbitmq:
                  host: localhost
                  port: 5672
                  username: guest
                  password: guest
      bindings:
        receivedMessage-in-0:
          destination: websocketMessage
          binder: defaultRabbit
          group: receive

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
logging:  level:    com.jphf.cloud: debug