server:
  port: 8081

spring:
  application:    name: microservice-web
  redis:
    host: localhost
    port: 6379  datasource:    url: jdbc:mysql://localhost:3306/message_user
    username: message
    password: "1234"
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/