server:
  port: 8083
spring:
  application:
    name: microservice-history
  data:
    mongodb:
      host: localhost
      port: 27017
      database: message

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
history:
  batchSize: 100 