server:
  port: 8200
spring:  application:    name: microservice-receive
  kafka:
    bootstrap-servers:
    - localhost:9092
    consumer:      group-id: message-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"        
    template:
      default-topic: messages.topic
  data:
    mongodb:      host: localhost
      port: 27017
      database: message

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/