server:
  port: 8200
spring:  application:    name: microservice-receive
  kafka:
    bootstrap-servers:
    - localhost:9092
    listener:      ack-mode: manual-immediate
    consumer:      group-id: message-group
      enable-auto-commit: false
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"        
    template:
      default-topic: messages.topic
  data:
    mongodb:      host: localhost
      port: 27017
      database: message

  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
                rabbitmq:
                  host: localhost
                  port: 5672
                  username: guest
                  password: guest
      bindings:
        sentMessage-out-0:
          destination: websocketMessage
          binder: defaultRabbit
          group: receive


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/